language: java
os: linux
dist: trusty
jdk: oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: "VXbdy2NCExuKKKeBxhhWR/VjxpjTH/dq8kLDn0Ia74JSRxCJxD3MwJUZ8t1J1upxSHORZFCcEdjUXEz1sW4SGCCT6vaqr03KCS/0VyhUiik4ObgaG/GZVJxzKKOWls/Qdy6GUaofd44SU82g4l8KGDZtpn9z/NFDXJp04NDeN5yY4jQq6W42XF58Yi0670jTMbhg/0gI0Lrlotvp7ZJIZt05PRIuY1JuJ4hxqp5kSzqn0c8RHlbvEEv2nqwKmImijUbtBS5TtxFNuz4ku3Hxr+yF4E6AVeIq5/BvSyGoH2qtJ/sQtltP5n7+IMv4Ujus8MPG6bXteVl38wYy1n3CArscME2/vwRNNPr00IjFkgRrUbVLyYkoBstZnipKdkCUAWLK9Iq0dFiM5iibS2I8VLy32tQFSoh3qOx6Xu9HqhjntOohjY4kGyKQIzuSgXXGB0xyHJi1EiWGM7MpbIwRliwd4Se5MvKMNopF7nYp6oviAuvtSjiuPBllQi8X2y3dGmaxIn05pV9pyz6t69E0MDGys72z/L4e4K72EjIMHuVpo9wBjsI0dyXrN/P7v0VJ76MXEdwm1ni0HshKlb3Gr46AZd+Z6veLmTAucl/kbGYqFOoXGIEakmKRa7nMLL5k0oG4YdmnRPJ5cZcxkRT7OZ92TqQHT+Obp7+qHTlU230="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
