language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: WwZKbbFmCCeULjiuxq8NaMCPJMOJokHngD3KNVWDqBSMDDIs+VpuZ25jkrixqCUFhcIEyxvtECZMB9bjfK/qz80VuWYKy03gO0S4T5JQmNsfI5nlrh2HdmCBLdZkXnEtK91KbWDbeN2fONgI+f4zjIcr+JR/5cY7lm68NzgGSeFQe7RyXtj5ouCBD1SfW1L5B2P+CimOF/XXINqDlXLfSx2lCx2zih8yrPmciLPYa+1ohmiGQF3zVr3+4sBCpPG6+jMNKdCAeqCxKTc6DhiV7zzJPmBtfzgz8uVWu2BtgOAW6mNV93qw4i4173cudHxfcLtbfCUDEGvBLZjOjq6cG0fspx9MbEAMY6NNyowZVKM0ixrpJwxRp/NAkTxLRMdCv0I28vs9E2+CYj1Q/kH4p2IVHs2EEDQggaW7nx16jjM3dyPOcj0nbULHrRkMJDD6rrhTJtiaiiUaVInvrJuFWYqxNRBr2pk29wcyRJwGCcJg4Qy+Vt4LN10Q5dXstCT6R1Hn2p8ws3jXGBWLKfzrPm4Txr0VXjHUYWoe5bezRORxtp1Xj5u/GdkB5feZgYTiXtIGFHqgZO7kbo7b9d/Lq+xFaNq/rMpnZXWXdeWr1ZBp7HiSL90yuQxzhPAIVFFr4nSdxWxD5EO/TquZWe8Ma5deFou6dfiqwTf2SOMGItg=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
