language: java
jdk:
- oraclejdk7
script:
- "./gradlew publishGhPages --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: uB5fkgAYZyNLslMXugHiCvojjjeNR7IXyXMQT3qMD9LZ3LRN+oxGiQjeZ4bEnqpUQT2k/gSQwsObUcuREof28CmMWjGWvbA0vPzS9FUqvLhqFOzO5Ja8iyjHYKRFIxDVLyPf8UJQVaiz32yIPfyO+K8RxPJTbNGwhm3IsHTw0Of+crd6Yo+hjvdle/uhGkyjvAG0wBMWHz0RIuoyfCQpxmFPXV+FczMqhIvG4Z7heFU27VLBOASwiNPsRNE2qeYYzXiZRBTHCqonFka4hhrOtIp5wiqJxr1RxmLhve8Hsiv/fQoKSrpXzYgGCnjFsjMeSq8KcNKzdsHzgdFIqgHaJqecvo7yr8QFERhl03EhF8ubNGiIFbjcgeKS/M6smUrWE3OcbrR8fKQfE58XGrR2yZFrve9XPBEKOFFV13t9PS+pA99tSS+JoGTijFxNpp63gvhZaMUcAao7U3W8vzIRatMb1PynlpoEF3r6GIpMopZcNT9MSluF1Ph5Rp9gRu2RxDY7nfXVlupLy9RIU92vhqCwpudrW7Fn5Q/S/jCqQoLeAROeTGxgnD/4jh0P6Wo49yjkVoVCs6Ed6Vh9Tbh6hDZjSlprEbIlPsx9xadU42gjNN46xQ2zLl8XLyG6wQ8BkB0GQYuLq1pYte9NGBU4V4GZjwpLnRs2vMzCSWTfHY8=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
