language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "gWe7xuPoHDJfwvRUMlfjJBTQdLl3WVXag3tBPdq+m53MqGmubyT3CkIl7oYCFCJYPkD0iw8wfly0iWXTMraR3IYHXIi8LrNtjGSpwSfEQtJL0P1sro5MzImk4VrTmqLbtYdDCjtvS4TJyaorpioE1h/A6ugVmgVCsfuOeE6mRbMPnpa1LHsLsLpl+ZaCJqnv2wFuPwduiVeFyEfoEUX1mdu/Pm5ASBI2Ur52HxYLRIqbsRQ/s3Oaxs4fz6BPoJTIvTw6OBuCx3pv4ycPIKrXzRN2d7BNErGwzeyIiKK+Ctf8hO2P5MbXFDvmOHwiizgTXd9FPmk5yKTdLfdgl+Z2h5hHhd/3GxGmUye2bHIGLM1Px9M8OMsESekWoE2edphvnu+Zv2syVwORX6pPYYBnCTckS1H0seYoNH8LOvXQzTgEIt3V1G/2LTKwPF0MLB4AzWyP+1w31ubufiMRA6f1pbvDdKrBpCAn6MSgsZljyR7GfLM/XiADj06iQGId4+fY/Ck9AAnRdY3zre4ZsflFx6kX6idBrY1/bGtgEO3M5iiXjfxrf0JKuXTjMIUFQ2u9W5rVnoOKnWbnZnFxSgCNUTgiK0RHf45ooW6H6fF1VY1yG2xMVkAsrNEA8uLsQL+duZa+WSNaq3X4Z6w/dPuidKQaCoyK4obkmjHeGzjX1sE="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
