language: java
install: true
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: GuWS7ZEkCnErZ4hcpwtladxYvZ/7pBLDWVl0LODxYyIdm6yhbq+GxGazpaDKbv3XP4V3dQxUj5vDxVxdcMMPblXyRtwsvNoCHmGdLSbi6NwKUIsUXsDoSDVasJl9ljMoq85jJlDzAxnPGQjHsxVOwocWhpZ0Ig74UKuOVRbVJiXTwZMhDAzzFxRR9UkASbFvyqavqC2Jen+q9w8APH/th55uEt2g6PD1ghSN21S188PVtTGWa7o7X9dtxPllj4VhBXbLOc9fR36idof78tMmqoO+vkfborQ27XiMoSkPifz6Bk3cDFzNb3L7CJnzF5pGqZrJ7zmwNmaGKwZe2TjqlYWc6S+80JGi+RFz3P3rvXUFOeCFnzz63uI0Hw/ehiUFppCrCBC+A0lpWBkb5IpSKW5efP0Iy24pmdI/gA6ikBG12xjN/irfU5RYgk3FDoG6oq3ZpN5GEUdarkhjHnRie5Hokszer0jU5XNDYra8bWL+6ou+N97O5GfNp9GYSpMr8rk/g2B42COnSEyQl53nLoovDqmuk3nuh1ycZDEuSCyPOWh6rkygrrzpOPbOWgY2HOEOtVRdY9KUG1LGY9HJ0Dnf7OtG3XK37CYNRt0BJ3DGEQTA/4GsEyGxioBAOrMTOVlcp4QwtUZPwblyYveev1OvCOsbcjxEQEfTPxVqm2A=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
