language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - secure: aSFTccjzmWC2h3aOkdx+Q/qrVFgiQPUm6L2SxZs+O2VVY7EpJVjfoKhLF5aJyKOrwOoyS78kaVZZdhPQd9w1p7u8jWT2VKHZh00K0EF2RzfiR5qNcgAFQ2RKdCVJoX3Y9RIvgMasA+2TZ2VhBmRR91W44JSLcnpkASA/d49+/6+RKOiuq1Un8gu40yZfX+V9qSv5GhxDg1rY0s3iKTkwsMdaJNbyVtTaYMN5QUZUX1LouLFEv0XF0gUov8W9QPfyeBkL0gRIL1IuQ1F9umW+fUOfN+sLdagw3XKYsDkij31IWtVTN8U8puqMHn6WotRRR3SuIlaB+CP0hz0dvbmnYh0wtfKtd5yc8e/Ftjrf4r7TTkQ1ajHN19kvXXx5nym7ywxu2/m/aN4sVB0m9td9TLhHw4UIJ60i2FqCdk/gp/nzoazHu/+Df55BO64S+0JGiyrzm4bqxJ9WDT57D6IT9FAoWLoGiM2wK037dqc3kV4E66I7xVHRc4KAmV5kpY2zKinJtQo82tTdlWMSwFE/3rVJ2Ryab0/rPabTURqL8vt+vduof9yNIolQpSGpq5v77HDNgid0fxVFTRhf6g9ebQ3NOw9QaYZz+c3GTx34gGzUoubsT3ubevSJNs3p0ku6GE726kxVEAXzVe9KVUcuk747P8BzTVmZ3i3x5HhhEzc=
  - secure: cs1m0tr1s+QhBJdi7bneoFVox0BFV3NxunX6CoupnmniVsTbq4TcMBhN2/9qbuoawfYZa+JggETUfTaqOksHEe61kqSXSDOO2SU2jtQIFDY7WReZlY+IzNUJQN6wEJCUf5xGzW6l9rLp8kyVnI5m5r/ZZbeq5DUs0ZwcK33VrF2/mcnZmg+zDF5UEKKIW17B6C35Z0qopogx3WLPuXh/b+4q/c73Xiz+e4nWHD2nIarJcWmb39kaxR7VOC8MwrT5Sgkxxz32AFdWbO9gNVAtwT1p/55wm1MLRMdgQxcMyo6C9LrEa2cRk7Rv2zM7yu6D2s8OdKLvnkJbb39suCNTpmtKJwsTOtSm4dnaFhsfQ47/T8wggoo6CkLayKNDWJwB2zHR/jHhccSW9jn9BD28wpBjYE4oKJ55UPY+4sKq7Qm+8L2ngSp+ZD8miNDIzKYjjezq46Rt8AgC6SYRgTj+V5L/rU2h/TkbUzdyKBK4XihtBri9ndid9W9mJC9J0PfotQ4EhGyB8dZjk6In4H9wBWv5/SnDNkr8dtyfwDbeQoBZ5V0ROexyX9nRx+Pps//PLGGOFG70/WsZzefcSyFDrGBng0CKdG90CC7Pz++D+EDoikJ24BXAoR/S9vY+EEZkoLI+z02BtrN13RYg3hoxRdC2afBQqskAq6cP7ydhuC0=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
