language: java
jdk:
- oraclejdk8
script: "./gradlew build gitPublishPush  --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: "f5aJdX67cYdGYoi45qmv2gOeJwt5AsU6CGxtPWW5WuHjAqdYqJmujtvvZsgfHtFLdWuYyPeH4hOHRwMNi9GMiFoC4MbVNMzTwOYR6KU77Fyf9bQ6oyD4rRQR0Nv2gMT3doh/891/uSgwQAdQPhmr2137OPg8RaYKm/9YMlxOxiAHknd+zXjFwIzJr+cBaZsVDXcv6cNa4h9ZL1Wo+UV0Z3tfWczAwpmcNoJPASouGrocxvDjRyRQ7ChnRYlzh8dKkNJHm7ywhvUlyiwUf3IA9roe4MGl90EPbaaATvXRggNev2HpZjgWFNMHvrlzLtB6UWJzKV/InE4mJMwWTdr09GnuJ/XPAa6xJZz96WdrjgTG2bklALv56M0oH2fKd1EpZA/l93o+4q4KU6XFKHYSVDpkgw7MWqspxHfUij5W9nNIjZW27wzc/ZL5bpcYtOL5y8ROdlQkxvk7w/RYrdLIMYibt/DP2T95HPjXro2+LwwX3kFh/aXL8IrxAU5Tq0xOTT7l/Ajr0YHFsb2w7Cak27YaU04PpiNqrruQPU+b8trrd2pgkV8lRFDvTfBs+hjNZCXjuT2UggEyNbM7A9GgQTz699PE90i0s2oG5YQTCYtfOa/WzjB/dZ/e5NHZtTpi5BBU0V1TSGewBNeS05ySdtMW+9pJQI+xtnkSFRlq6lU="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
