language: java
jdk:
- oraclejdk7
script: |
  if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      ./gradlew publishGhPages --stacktrace;
  else
      echo "Skipping publication to GitHub pages for branch '$TRAVIS_BRANCH' (PR: $TRAVIS_PULL_REQUEST)"
  fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: plnnm4T/0x5p6ckkOMPwCV1q9HHHBUukJT6vDXG0J62vWZb+6FxPI8/Qpv85/EaxlKjfav+kpOBUoSg5oPZB/fwo42kcqJ/D4TVH2tp4rPT39vSn+Tk9yo4WS74xBEk1vKkAZ5s9N7gO4+wim5uwNEPp98+hgBacCRApdzqOeprAMe6rGhDyTDcHzqZMGiUq0hE3UPEBfjK+fQZX43ahb7VLKKi9xjWdecqi057mnSwXPgTXe5Ovcljo6CLAyPBwmKyaj7/ER9wfGw7k1U+O29WZ1g1UONytcWwKTtFF7WamyvwWrRb21/C9dzln9k0valef16adjdHSu030VAmwZoflgR+yg+F9yv/S8YbpzBgdCWulrsp9qBIPoExxyzzfaVn/LRx5Gf3WR4HXSisACb7BUkK9wmCa21wwViYGp4mik8/Qudq6XGyVWn8WnkBQkpOX9EgNnq1nLHcLmAl/f7z0woWM21ls6gVYqbFbU3Lm5AfX5vtpSYWGkJQIMWcXXsAuZY7vuTspyY2H6NRnPrICYedWkY1iquQCbqFGsACI9TI9R3K8g23NvBDcWctQSjXp4tRDh/YiKbrk2knzNz0clakiNJwMDc/KbHGsTwJasz7BGGKugTGOvaDQwofLUNAo9frZleAHww+b479cNzeJ10hGG/FWFxsWpo0seEQ=
notifications:
  slack:
    on_success: change
    rooms:
      secure: hx/oNOw07nsrGWvO7TATQA+Kg3GexQ+W3OlRsN8MZfRWqTgsCwGSm1GUPKRBkUadXYiYENzzU60ZIyjBek+5ry2PySS9mVeh5NYhUtlrVdJR8z04T8ZzSdbi+L8aLB1LH/5UWIZth298RqyfK1AKXfhf1n5dTM0dWiZ66v8iQZUh23IIKMZ9f9MAaL6xRph/Aa1JdC+G9ZwlT/VgXKO75oe2Ww6JqMvE0Oh47b7FXuNYRgLXvci3nqLRGe9uDW/rYuU2RRq6Id07vRtRfzpPTCSm4ojmced9n/fTAjsr4diNsdKfk6eq3mGiLdCB1iIsyOkZiSCulXZqeirtG6mNYTK9xZrqSmW3Y8PU7peVGGkgBqAJO4Cdj8sdYvfaWxMiElOlXqnJI02C9KjZ38tfNCzjWantX6y63vjpl0yrWp7CPejA/O5T9+C7dgW3S9dr/gORYfNNCLYmSDCtwkM5U60dtJeRd1oMzupfY2I65BYeFkDAysXHoLo7OLnIJK3FwYpb0wsgn2DlhTEpgrck5TJGbUPyw959EzplrTxCx8cKF3A0LCMOKhVo07gVguyAS2n4vOl8Ec7XRtoGg4S9mJGKgsZBhna+PKI4gqovGETLUpyAhgw5+JJLfuTbdL6/N25nPQ7fff2P/5QevZBD+jkcIYHBnGjpUEuRvZPPczQ=
