language: java
jdk:
- oraclejdk8
script: "./gradlew build publishGhPages --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: J2QpVeLeAXVNXXuXX77CgiAijO3Wgd7ujcIx4UW+9qs5/ZgFoc1XBdFo0sYxqeVl1GtaRNXo/1LwLHNAvG/1c5nrTK3hBdgo7RWASHFvSNMNsJnJvEJGW1xAezX4K3/bJHHYFVU5kWDpODLu2KhXVPKNoGPCtPa6pywWqgZ2RzDBfeLYORejskXOVAr3nJulozbMUQCrNFyAgjNY+s93WAbgP/T3X7vTIpZiuJKzJKTEFR3jCVs8X1cswxpzu/kqpiKjx+14Xb5nZHsXgbFaQG51go8Ks+NkpPft66t8i6YkNEUBCkAaCuuQUOhYsvcFmjWxzigrUbdfjyVjxnaRWEES+g+EwI/cmmUaBUQcQAheOm81eEuw8mqgWf9gMBY808KmDGSNfNPQ93xBYB8wD/h3s4SS39DpHOIAMuMvj2x622qy4bsgXZF8hl+fHpZg2pzvPfiH7C7Z2+9vQUvyCg7qOixe02hXj8Xe1ouky6ADnXftCJT2n8ebNMIhaR87ZiiRF6dNqUtT49HAFzfWT/lxIkxtOjZ4cYEibq+VEHsnyARujY47whcAmHho8tWRrcxUa/DiZGxdht443pIjFtVBa+rZTXpPk+Kk4tjkzUd7EAav5YWfJfCru3PnuOA5L0qopHoWwKVx/zlgSHzunFEwTG4cYXF994Sype2fAR0=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
