language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: B2gKApfhbxKM2QnKoZITx1V3w9v5vSoapo5puTWL2XJNetvtchkVAzG33QCZ57KTTsU1W0iLHr3/kYskWxDfHEglR7ICvtyRK6nlq75BNWpgZd+YVwLP0/QINb2GHYseF3+Ai6G5+1X7Mct4m7xjlsK5wpprmyNHpRr08VmBs48m3YXK8GRx5uwtQ6fe47UmkvHNVCXhpLTUhSA2f+zaQ6ha5I4MwLlsjsw98Y7l71Oz87aAuVG1VoAaGAAvwjvlOR+u66Ix+W+HXw1yj4r9XnWodnhFp0xl0ru9ax5ox5a/vvoGOecvQAHHQ4zlmKeXAXHq+dU5D0DBCOTJ7U2GWVKJEsR1xkGWk/H4i2dOH2S/Pm53/IMdIoubgunJhw1Fyh0kSQylyEtLTTJwzrHhvAgLaFpfSoXCpPV9gIhcY05ITBfcgKjz1mzXQu57g1FPFoGZ7itoBJDNtMthshMPPgJyqMJlFYtvkTD3OkwTwQiXOgty/hWl+YILL9FkxfMBatC8IvtkI89TtgrwF4Z1cw6cxNO7lRnKH7msqE66Xn7aRdymZsYETPtYuhARG9QFUvY16lwSiT9kfYM5WgIqAWasRZFKZUYUfAxcPCl/e3GFOe5DBSd2g1oiXpRvCLkaUlqUCeWr48V3PkNWTXYAem1yFBW+4Nt2DRGptT+v6mU=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
