language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: mxB98wwT41P0J5A0NUdmVgzXA3Z3m6idzoEFElT0idiWHHrU/hY0rvGUMEJN6wTvuhAq3ZU4dNmaDOttBpfkPE5jKNzGVyNPvELblnDef9uqRpD4TXHR5gQw00iWEqnWETxag3Dt0UeKcFPB25EFU4wvWG54SixMkVewTy5G0vrnrfY8VxBzMTKHByzq46KoSgxSfjNNyHxtq5/4V8nwEFlo8kleWRVVvh5DNBFk4Qz6Gxl0a5Xdp65upu7Vv7CGWc++wF2iVbZ0cZ197duuYbgyfcQArnX0d02dCZyYZE/R+joGpQaz0USUFTf+bN87f01w76v1udEiAf13U19wRKzScrO4q+LeXG7YhR6fao8+s4KUqZxEjVZOQWPLli6TapxWiHnD0ZrDhOGenx0+QVEQMjmLKPYih3jdeEXTGoUYq9BTZaKFZ2S+qiNKxiyNhqoHRcUFCiIidRr5NbqgboOdZhDpvKp26jEOsEjmYfrT2lZD04/2Dw/Am5S/qBrvpj0uBx3dSnNFCfRPdj9uo8Bcx3OUoZRvtspmqMTcpvGrCEhjFJuIff5s87LIhqYQdDjyf99/irZNcEi0VBlbePQGRoFyzb3Bu//sDztTs7vUbKb0L0whIPufUWH4m9T7cyClklVA4QtVaZ7LODdOSlvKND69Tz4cjeJ0Q9rx8RY=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
