language: java
jdk:
- oraclejdk8
script: "./gradlew build gitPublishPush  --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: "bjIk+P/9nyfaoiqhy2kJjV8XGoyfsN6LwV8LJm6GMMP2V7IJWk0XGmtTkDvOOUKing0viOifGzhdhV0cPOIHu/7z3SUaz+ib/o4I20xuYQpN9QZy8Zfh5edBengtFt1DwMMNXOGJrfbQsDgy7ka1tJW+D4vngs7UoJfGrJ2uMVFYuqEjIUzPWYiwzgTne37j0KadWj5XVBE2hLC/LUV/+s6dVDXnf7EzZ/UiNBSU4acuZ4D4F14t0FKUJad+LP/Et3Obr0Eq7XYnHv64Oh61XhIckNnSO/ZIVNC7dwy74gUYwQeshJ8UeoKIT/wS9NTj+zW001CMdpCmMSiIy4FMznFLiRZ/A/g5pwdDi3FUXHOI0ro7qy1WB/z/bovNOASr9yb0lluIpjNg4V8VQzJYwA0itwTpC5kWmtn044wR68I96Ct/3IYwZPOxBmFcbiM4KydNStrV4/g4nygCp9AhArVG7zseTwQuSJFDU1Onn3AOAtL82oCQAGgPD8IafAzRYi78eSl+N0Kgu5YBiJ2KwJm3Ihd4kZu74gKeUfpBdDOElYZ4MREJJstDh8zxhI2VDPZh+164YwjrOIhmtV1L2OKu5CnNMte41siDiP4yixAq+WETbX2UZd3JOiRH7QlemAQ5sF1Z6WfoB5+h3lrUBecExz5fIC/QBBvyElHaCoI="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
