language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: eSpiy/FUheQKbQmmYdd6apB/E0XAYSjpACBvQTj4jeoc4DQSNtyHjLD+rRIU+d3bUqQgiQPjtS7c8eIaY2djIDlunSfLC3/irwqSqmslxPXR/dT67ggmM4dS1wh9jiuCROiA6IIS+fWSz9O/LSqP8vLgkrC+np3w1HkNt4TtsXU+Et2TBySQ1TvlnKzdvfPPifGK4Xn9P+SKLBmCqHXnbI3kLMOxq0MVpp0Siz9fweoaDF7eDgl3pjfpmqvIKy/d80HpXtD+NHQS4YjOMNN7dGCZgDWg3GQzVvA3sjBDkcbP++rTUHaZ8pm9h1gEFE7r3X34R3AqOSXXjryrTDZl7UY/Pyt3K6TANUl8nAxurRZHGnYiEB7i3+cDlGbbzd8Y8Q3STCbxbfkhbBvaupGjZ9OqCSNcU2G74VTC/ZXnFxiDGO/ParfsY7ptIIkAQqd7N8PF99tSy6wf8ao+LQg4BeXGbI2JjLhjNAJkjRchf5pgpGgDnE0i6dC6jjN/Kc/EMfAeZj6MMZ3cICffkpFL78VtQ5slXneg6TxrJxGOqmf1Ka5+U0luvCwFKAGrUD3P0xOSP8SpZbpOHrkStqX+Bhda7YSwiveUh4mpwRg0MGlQcQs26mk3+9KK3ctZrN5tNxh5R8h4iLnxdVDGjRRL+StOFTbxsYZ8n7E0XFIggTQ=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
