language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8.3
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "LO9AyqlNZghzKRACQ40c79/Bxg1FmHQ79YT+0I/xIkLmmJ1/KyM3Qj1QIaQvuz9lr5zdHWbneJ6ze1ivBomq83t7sCZN4WtFooYda8l7+89lUKefUdqPskhA2ky+t4ZJ8X+mxeqMGM7DwfIfZyHlnwDZ6d6B5J9oXjqCP165yg+Orf1xDJl1L54fbKAjA7kXtw6urnKawUNqzPD8WnVrVq+YGS/hacqxgCTg0ZQYkCh5c6uCaNbpe5cx0Vey+FelSnnmOQ2Cg2jYRzjxNCA+CbufVHQQaqODmdeByxZLKAAwNpnSss5uPNZP8JhmVe42HocVOd1UdP0lzeo0j/9F4rZBPOZ9ulnbbe7mxTOD/IRjjOBcoX2Qb/2kx+8z8pNch4YcExLNQx3FedMNj2I3zJWwIqEth7ZmVVanWzPrZscaX3toDL3YscqeY4bjJv9QR+knYVRmYWC20VVKLx81sBfx+B2LrWwuJyFRoiBtym0p6fb56QcTJZShAkbLW9VA7PeW28G4qn+goS2cnB35y2JDph7ZoYzmVGyX6VxxLK9Ij3+OwlaFkWJlcJkKHSu9F+zzhQ+ww7qS5k0CRnpFBxrO0t3cl9te+o4moVSeEQFf0JMU+Lbys/4Kuo6glAwei6J/dqL6YnGrCqS1nbUBoNmwV7GhxcbyM2AcHlNPtnE="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
