language: java
jdk:
- oraclejdk8
script: "./gradlew build gitPublishPush  --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: IKFndP9j42yq6wBCVLg6b16CQqMsbKV3m8oyD3MNNcej9ALsaW+53uylxc0gIQcI2BJ+vo9YIJC+rY9picmqzlo644hHWpBhrKWO170L9FTBaNMc13l6V/tP9rmVyRwOnzrpAe8x3hfpHpiniiNvXZY5fG3TpW9tExAtSX9oQOH+H2TQJIYXIutr8d6zWTCbBpenj2eklqCK+M6UhuXgSguMpeRnM0xhFYcsy37vBw+qdGckYmBUJPtyKNWDivb5d0/3TFYGxBvpUS+oO0ih+2jNuDrbamK7Qmh2ew8cuSgPcB387XChKpwLK9EJ8I3blq87qz5WbXxo0qhWNq1xakKG91EJ7ycKb0cowHClyvbHdJTVRGR/Ub2Yj/cHuIqKPnJBKlNP65cv9kNCKrEq2HoQm3kbjjJTZtHchTGR9vv3XjOdUTEqrkeVlBQiB6Zaf6QvH+xFGMDFPRk9SUCZeEYXHlXYqb8wANZWrR9gANEW7D2YQvk8/wdXl9M2GvjpCEt2o7okCl+Vcdwj019ZrubK3k62cMkKo+XEzH3unQ/2c++IH0Xobc/o4Bh7BwvEJSziWPsnSBF3B9WmkxLNBTAz5/E+tMg6KzDrHmn7Tgogi2JXyP2slz2i3JBeYqGrdBynsIc1ba25VD9VgTUzUFt0leGnCmb+ElqE6Yss974=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
