language: java
jdk:
- oraclejdk7
script: "./gradlew publishGhPages --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: h66gIlfSTL9oQlmSHMCXg43l0FFxtVoBJBiVGXweTvg8Bw5LVGe7UKpC7AjyCsOaX5OdXsq6Y1XYXhrrHii2rHJnn8iNatg/4dJ8ecCd4PJ6kGHj63tC8bAQEn4yMTY58FMVGwT0DooPUp1qI02Uv89wG0bRp+9uA8w/lLW5aYY/uAeyd1kS+c1QN2j5YiN9YRy2KnA58UNxkuJSAOAGJLfr7TX+2LNXWjcrFDEOHWPHWqT4tMP0r1g3w+7RAji8+8PUp4mQkYnk8qG3CH/bD4nfKujPzBc0ssxCKlSdcG18+5WCOgGgRGNmMw5+gBnRwOmEMS8SOeMbIPJV21UU9RfMGx5nLe7aIeIHw84aHhunILJmhiKX7Olf3ztQiWj9KGUhiPvylHVtHt9+a0bOfoJuYdeANsdEsL0PAiIARDL32VyGQuSydYqUaPV+68kVYV03EE7iQQsLSx/tLBwicaBxi9fmpg9YNPrTqDYs7skqTKMgXwzuGJ5KzKyME6X0UkmvFUq5WSYSEfNOlYv7dvXhYwCW9Tr10Mmn/wGyM12z8YIyg5DcQLC2WmL65SFk/OX5VeuBdhepepIrzgjuRW2V9rw54YZITQG7cCGITvyIeydN8UiMCBEn9K/mP/izD4+ejmBNlQPJ3FAOBoC+v/wySNqhghIBsrubLJ5PTVw=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
