language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "bHghOK+UXLooH9G8sFlkuWoqcS6GdX9M8D8lyi+sLoC19mABw9y4038ONeV43vuGI3VZDi07XA1fh3lo5ogYRP4QqJZQoVan9e6FcUDjX0RmpeptrC6TXngYL6cjbINS1xcJgYgcEKUqTHFM2az3pBHgVkPzKgEP6w05EbMeeWgxzGZ8s64JEj3LabKlLItntYvE8ugsgaviQS0+nH2TpaXMI/5jxafHDEM/Y8mddn6iQHrumI2tqq8osBy433B5TuygD4tx6hfcm1pYTfZ7fqYlBKI4e1chH6wEgzOCuoW8HcSGGZBiGOFW5oPUfdtarUwl56KIHv/JVzCd1mvcYW8zAVLSCRbKFjNOSE0mJlaAUBpnM8oYfFWlXPxS1S6L9uC5UspauAG9vFsvjVFfuDOgLYpJQLwX4iWLurscM/IQxo+rkRD9+Q75Y9ceDvsyQVxUldhnubX6AIhxTf+3iYNEOj7YWbiYgSwe3MABIyhmiaepxWiziU0R2h6ZCULck3AsgXjToo1ZXteMNy3bH83VWmlpbnbQyH5JuS2DL/6h4jeFjhsfxiK63AUmr93z1Y07HreRKoyRg+MTycLWXHrDlBPb/b8O8rj+itann6xsXRrSow/Nq8KiMz2bFyn1+oLwqtcX8fmKU6BBfmKPz7MkSX0l2dAEirD90vi3IIE="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
