language: java
jdk:
- oraclejdk7
script: ./gradlew publishGhPages --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: QNgelYXYSiDIWzQJge9T7Xoh2J5EkTxnfNmnxb1UyJWH5nWS6qePZCuIArGUO/B/BXfGc857/moXyrIg8tzREqs0zuZlrk0q4aVk0MEdJQ83x51dR6I5CgJFQfP1qpn1zf9Q/mud/Vm2u3H0/zVJrYj5LeLydqttjsD+EYdSE0UjGA8c07DBJkLJRpIUl3mnfxhr7c++0N5cHCIH7FJZow+VAVpLExuTkFWJ45ZSvWFNAaDOP7jrZfGh2j93LjBw2dS7vNbwcSsPL8WJ7SRdRyBlQREY7nPHhSsaFTQnJFTVTS3BpahrYHNFysRPPihtOdJPvH5tU3T5XS1Cx1kSUU8shgAS3crtwuz67uLZH/oaWnOuBLdt9Fd1quusX+dPb0MBP7QkuEX29DUtVFOIzzwFDgLAhkZ+DR+AaGZRww67SFH9BcYGhNJlOn0vjBQj+aaC56bZIHPSbGQtydZW65R+ex1VM+feC23VId8F5EJBgEv7vZIsG04P22+AqDB95EAdRQloumXB9nVDIYHlgbox7G/xiJD78boEfNNiqxcYOdyeMAe59opiisXJ9YQsBp2P3KZH+RB80TiV0FUQrMmsl3lICx2xCSrrLC3EnuK5j8MKsUq8zf1T2wACdmGLPfBpnMygGCNe20vrponh6SmAa25InSdaZghpEEUIf0c=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
