language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "auWYrCdMtp8U9QIzPOkOkNBQE2tsCMS+8uYtJFZgZPhMPZ8MZl+veRZfxQ12Q83qagT8mWb8ttdxBJ97bPPN6oXKG6QrVGT+oHG4D6PYdlWEmp5gceZmA1QfQ56VHCeX74N7tSkbbMEB1MFUMqXswFBNWQPH9oddmUkD/fqS0W5Do366rwOwyUPrComqg9Cpa8Er2XRRNUAOIpIk/exM3UMgGclJqojMhIv3J609GM1RpMQlFCAud1Q3A0ovG6g0pU4WxB5vlmBCMH79veRBtODgWiEAc4cz3QMano34L/SO9a4ncaQlBn/m14EiAkJilNT9Q72kgfnvBTdOkLjWtiRg3VNAQJRtdA3iJEhuDii9rhFqPab5wQYZpIhB5ccIhkeUHn/fU0Y+h3DKPMqz0CT5pwMaL/OgjRpik8U1Ze9AxomVvQN2qNl6bLyaPsw6hv/LINJ9jxwjOa/BO7EAiZRrj92LY+j1eRcdOC8vShWjwL9rclgV6LiQ5lwXDSaU3H7Hx/WFxDBM6tA/V6j+mpnfetX5JwCMiSAnEftRqxbHOvZvEV9a3k6CJ+ACQKExPEX8p0P8uUF5Bq9Mz0u3XbHkaBxB2geOsO/5dhXLbjKY89oy90dVGjqz1S1wGWALGiqcDkCO8PP2h0F2e6FTdeB3MWOMqyoOtlcpFT+AGUM="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
