language: java
jdk:
- oraclejdk7
script: "./gradlew publishGhPages --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: IRiN8QiCLUNVU7pLkMA+pb5Xd1NaU3+47mRtZkOoGvmOJB2RRVizh2hF3pcvWqrtKMVa9PSWsDYp9K8NuZJClJBCZLZafnVyzGeyJiIqw9wlmGTBz5/4Bq25KqXUdhgTLF3JfzkpP/kqNnoAavSvXPifXim1D/pkkprzUW6f7RTzDgLwD8ornWC1XtMKhfPahkRkeGvKYkMVT+33prmdjjVAjoJ3GBkRje0WrF/ShhhWvtuxZivdSMJRx0hWcri5EP82qLM/QvBJzp8jTv2DnjVImGqLXMrsJU0a2CEUPF7Qqoe+ZaiiE4H1lfTuJKtsuA7YQLY13wLgEtYDcRZvIvDXj/IKBSum2y0oQnHRFnBw7QSsne/Pwa5qDFwnBibQsMzguWrCJy36dMqNkYX0QF+NRDT8CbDLAFbYf3QjmfshdVHQbQ8mT+wNVmx/2dYrocFd5bz4Qddv7P/0Vz9zKv6cCZy7ESPqtmljyiAThV9CNABZJfj5IroWVLgfRJAyAcexj2zCZlSs+qmHuZFcMdHHYgHWzF16SM3yuiAJvA8XfVM/AAY0pCwuml4aMKumfM3vGOrTkaDRTaJCkG7Y/6PgpFpyD8JZRksjU+AoXMdW8CNLd/zA9fksHyp9VDyH6Bmu0ri6RQqjyvzfjCER+g2XlFi0xuA39hjQZOwwnac=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
