language: java
jdk:
- oraclejdk7
script: ./gradlew build publishGhPages --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: C8rlRfo0HLibOwiluCq82T7XJ9O0/GHzHigfrFzb+W7X6uQSmi3xdydfR3gkc6aE3zBIR1fv+4o/nRiytJZZiQF2WlsuDEtByzl7fSYZaWG4hRGpJwl8ToQB1i9EpNkjaGlYwPHeSReqeGnvjZ/Mm/Qkoi63S0kr+2n27GJri9RHmFXXtG5bcUh/yznZkibn2YadTCnja/C4NPPww126pQffWuB0otTZfmjUWREnNTo5Px9X9oSxYpAj70G8C7wkJOUFpIgaUmCY8s26gMGWN3m3KZ/ohPko5XYO2/vZwXVca65TDn1613Ho1l4i0t65rn2HrPlewF1FoeN2CQMJFPRAD5aQg2Q6vTjlZLeLeoyLimF2vsb61IQ2MgsHcwBmQb0Bgt0fTmtLVttpZsk8XInIiRqafTCR4LESdKV8deWmJm0qtver2uvIjIjvP2BI/JRuPF9NMiFzWDEnpLPsro3WUApSvGnMcS9LSq8Q8Kh20tnlQ4vepNVomZNJqNlWDJbKkWVy9eDTypWfzcdFLoW05u2MyKt5lRKAY8b89RBVxEoX2dE0bRygEWWt7gs0tlxPY2/O2fyObXscc5rl2FEaCXUGPfPrF5dOMIBro7/7ulamfuWEKq5ANp1xaE9TkLm26NpVKo2QIPF+zxnVa89QaUJUMQD7AHeRaJtDrCg=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
