language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "P2ptSyPUVSuaX+Psy3NOgUE7lbY85vgmHvMjxV5395sg4bBxL+gMEZKI/BSrAMufR/J+75Tx7OeM/6nIkYfmcvAhj5l/BrCGRc86/N24ofBcYTbI6BJ2jaqihNLg1Dq9SObSbP7unc0k1Neb4DgemNGJyHCo4HOaZwIMWgMfnlzp4gOb+4KQ61wa2Y/QlvwDdw3djrapS80rhTOiGUlrb7kx7NwfeBV35F0owqGJtNzGi7YIzs0es/TwmRvYoQiVECp5IF16vZB6yetD08RIJQrnBeQuRn4SpqPpyOTyD1ybzaAuDH275iFWnol+JlsiuVrATdgWiQpj381/HGUSFN0H3zfQJyALQ2vqScHmfKafl20/FZCJxHnMjUGECgE3MU+yRWZK/8AM3aij1BVeL41/Y5bAY0E69fFPkIAyQTyJ+JOY0LHJheqoopFoJEDYauVCYmqFZFTeAbs0jObSBa9X3hzMYoJH0do0lVlj6sy3s2dPKXmytxxMqmHEbKKEFpNvinPLxbBGnP3n9jd6zunAenucMh8dhQOgJBBZI4yz2LRA35GLLLzB0nwagBD+9kdBL3jId3+AydQ4KSCtOv2XNFUlrvjForr5i0T3371mmI9TbCtGEcgY2f51Fe1+Yb7R3nw4NhnCBYTLYAakwrsF00fa5eH9NzIePGsQUu8="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
