language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: It8MsCqy9YGHJVbc9sicH/fytKdcQ0jpU4w/NpDRzet+XWo4Kpt+VBA5jc4K25sibaJmOuN2Xd86how/jwykkbaBjGUP1VmXIUsJU3skcx2rEDiAbV/TgAFN0c37yVPbsfCqyLn6ZaKQezADu3xKjmmAG4y1oitMk229ENbn1fmrTYRfs0Slh8rVKpl4E4hC5nau3QnPIWE0zptSlieLyzti0jD5qGghFlCXBz6Uf/yzY9pS4ATR6SK9TDPQ7VQ3ahBt3dzJe0mh61I3IsuabsmV/i/iQX3rFpyf/7cdN2LWnmkviLzljU3ebJScnpcKOUBZrJCXkwYzi+S4nbXwt4QeyoppuxxzctaB2FEabIORSjUfb9L1oTVaK+ffNwBuhGdj7P6fwfi0QDw4KaoF1Qm8Iz57Atbq1LJFsGBsbAi3EC8qg+WwxwMIq/SXm+YHgSqiIYNwC0+coBCcSGBCCfalzb2wktnNqxv67lQgzDnD6OoNMfEM3W4o1YEmaueW81EZe3cv5fVGv7gvxMgge8KKfSspgMuCAwEwTP75WN4eGaTDSOQbePt4IHYWEVS+e3wETcJT28AP/uoR/+acNOmTqRGadaMxqqhXJylRtTxveBJQbICEuwcCL0isqL0NNiyEusOqRKV6WQDF5zP/wJ5bVt/14V1EcRw570eBSf0=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
