language: java
jdk:
- oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "T4KvgNUPtDwkKf2zZ49+OBcDRNfNr1ucvo0P9XUuKNRkw9trkFugcfhXKqJHOncms3N2Wjaw5H/m/EHjUqVb1M3J9Dvm/tQL4e19thGojtUarMV4YK0vJxZSWkCE142yEepijb8cATO2klvpzQDX4C1Gp702P0ZFn/dtUairqiHkyebN7oYIdACD1bDNqqmIq38+zY5o6w4B80dODpen87Pcbynwz5QGsi+wMvxwH8GagMslaKyPZJImHEYt4e1z5Vk7YgESJwsoA8189oOO0+67MhqkyIqi9qDrx5XZZx9QZW4lWdLAYxVtGTMvthFw4ddpsYb9UGyc0l4RlzTSvRde/XsAmZjMgyIoKwzRUBmXtSIZ55gzzYOMdSrB/0j2VNXiluGsdqbWNdprpqrEJr6luIw2Qcj0o48FErb5bWCJZUzqTr4bKeUwPhR0v0zbOyPvTX8VSDAcjleQyQNz/unR60STy24i/EUq5VYHgQHcsepOPU2gQqi+d8LWb5dDuWKdBV2GgkGxaXYEyKaaxpf7Pksqo3bx0+6OZavjN1S7hQKOesbHwqGxJCNEIUAwo+2wssCebZWsbVZywYvjVJHzK0O85rbmJ/UzAoJJjsNMRZSIEL/nWzz7TZP3DR4xSicu4lUmxKHxYM4bTqe0ps3/FYMFkX/CcJrf7mtGgJc="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
