language: java
jdk:
- oraclejdk8
script: "./gradlew build gitPublishPush  --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: CZawAaLl8VvxStdnaD/iFAQYxBCr1Y5R21GENhjII47qgKSQiNmsOKJC9xe4QtgKMzBXo/NFbNcRlJGACp1a6vHAWf/NR00ShHdRd2g47H7aiNqM8JTiT5NIdpUZx1HUQQT8K5NwRg2fWiT7fxNAayngm/DTJbq/svQXrnt29FaBvG7dkcm7yUq2oVPGyDBJ9vgJayrIAZmg75Tf3YNqqeCIbeGWvTh5MSCIwq8OeXg6l7v8+3v6ZPw4LilV6xg15CKVSVaj5ZNc+Yl5In6kRGARZkw18Ta6EQwOLONJHvJN5cmNrigb45e/pwFIwZNlap+58clJdrHg8O2VSD1r6aLh1s01+bTjjS1Tcy5BGY7DqUJ2lgMh1ErIvrXX4xIHRaPBfaSFsRvWsKzLb9+fAWi4pVixkr4tmIU1eUtignXMsxjawowu4DLnfIppxEclhxZNeO2AKLqGAq4BQeteeojRYeTOn/scZmoNDWV/i2fsm/bVw69WO2sUVBg2i5RupNRmT70NwGxTU2oFjakPseT4cblyI0XA9vWyz8p9yu55J6zlOaSWz6NIYY8Jr5vMiTd5t3jYlr/nfPb5P+zhBZDgwgCRI1v4mcOUo3NnBRmkrQx6c5wE/5QPqyq/Ruf6pWe1vGGK+3Hw6nZDGOBeDkPa+PWs66IxLA0DfkcF+qo=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
