language: java
jdk:
- oraclejdk7
script: "./gradlew build publishGhPages --stacktrace"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: QkyOd2lLd3la6OKFGMTfE4ybmS6rnoiWMldKV4qCF0HoniTR2gVv4MPBHlXYlhpmVslSPT62rpQwZXYiVbjOKLHGllExGV0X72rxg19yJUXRgf/o3lNrj7y0XXbDai41A7UjCr1hUdcfdyk0qiTWTDKxzASmpM0z5LxfQD1qgeCUcHkea/jhYACo2l0H0iYHqj7EOS12u3F5gxTM1XHgxz8eVySpEVwcERyOf2xAPqmRliXKjWyqCq65MyIYXquQSzUfHasmaqI7wvpKAVYsj5AY8gWBedy0Dd8kpBmbv0INt7cIRz2AlEPINocqrncQQDBLumNXVT+mHRuI3mKGk2jLKjdhDIMqIRyYO4ZDc2wj42qH0eohkwJ18ItDKNiItGYEZgcfyjuNWIcjyFZui4+/s5A6gBlcGLsOnTclmV884q50yU5bcnDaG08J2iV1ty/bVgh2pM1tC1phmyPzxcLyQ6/X4T5k0gRXSZYNLD4tzjO1P7RG8jtnQw+ZVj1rWoWEQZkkGxzKc0IB8n5VErPj4jJMFp0YoHdXePQj3cakZsR4j4dPTA1H9WdFIcvQ5rIx6DvHRVpTt4s0EYzhu5mS3T69e3oW3a+wRex/277OWG6QVIcRvSTCkxrs8lkpxpkdL6N5aXer9O7WQdj1MlwiaaHGf4/q+jy8rF/jZ/E=
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
