language: java
os: linux
dist: trusty
jdk: oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "AaEVsNBQyZ9OSpj7brVmlgq2dRFa9flvfB8FUddbrIYrCjrb6Ffr0To5VLAnI12qbkX53tcLaqoxYITszlS+/BMczp7d5jgr++1XrxI082nF2MlnpuAf35uJHCD/swD98VBspxfXtV4KUwq0V9VxDjJP86x5SisXIx2fuQiPLYjVk0BBqNHq6MgtsgmRqt9+77UMGEfvlhvlRWbcNpS4z6fSWVBiIfJ2A/QaXP6iyk8pusimz+cizMsSAfcv2XT1ugUI4nDnaBvDrOWknRpXtB5oyit4ZfttdWL+pnUmQRO/7CdNBF+5Aeb1XcZT/1CmEe3UGLowxY6OxyqAapKscNpy6TMcW+P316MdpRkuHkv5b/6M3WsA5Rp6dwyL6nQYm4HNEQeZFGiIyvKlh0juJYIpkItzjEnUCLnj9VxB87pxkztyutsB5EII9FdsLROVAjeulPW3NHLgcWt+YYFFj078qORB6s/hak/VlHL06PKWLd9rlazp9YEWt5HgIzccz4JnKULCTUmDqMtDymapBvafB87cqLkNv7ospbImG2NZAZZL6Pb9DhMphoEaiNI08VKehtuR72rbBThXOf6tw/jM2bGsaSvPH0v27V/Pzjh7UeU48YhMKAWCNaWSMEo6dfPwZSnpGU1GILm6N6x+ZK6+vt6kFz4q7S/bvIVDVcw="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
