language: java
os: linux
dist: trusty
jdk: oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "inyvb2QHJhWRtBUZdjOHDs8ZMSkLYVYDE+1rcxVmy9rPQPBWdE/4eKxCTWVnz4mWzSpx8XvWUNUEQFkpcZTktp8Detb0uqZJenujt3uCRUsM3VcjFujEbBq05PDA4hB9zflWAhZLV50cysQIFpFGjfXqudkrGvHpCuf2yGNsRfkf/24n9WnyNfbq+M3fJ6e3IQZHXun+OB88LwfUH5/Pc7NNsnRhG6HopOzIPEsPVXMcJLe0rQUrrlk5D9UZpgmF6Srn8Bn+FBQMUAtpRIBnkr16WyyXJfAIibOKjQ9sk+j/HAK+ybFRKOuy2dOL2HVb2GpKKm5+hlkWMxZ/kPQRMGspvod9XYc/WKqXZLrb4wVpyuxdy0hGR1NbDVMWROlVHfQFmwacMmbKNp0nNTOCwJXe2ILsQ8PCAZCHrAyikgfwtWa5sfUwA9CwO/YFLJXA3/cyR2QgMQlEXfqrus9GWqVcd9A+9PaGpZjRCPrHioFJlIA0u/hzCKdZCSuakmWxc68Gte3F7lje0kJnIuGaqkonpiq3LcsPM461gdTHjNevDML0OdiBvtGeE+vILYlMMq0reYkyv011BTxcX8mws3VfusHvJ5ak9xgvNsfD8kHvpfIMeHgLnU9m5SuGLVvcLxSEpxyrkNXCO5XVUgNlPmx+L7ZUVBaY1AvFMX4eaP8="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
