language: java
os: linux
dist: trusty
jdk: oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "PAanY+N15BbhHr3DHnuuMtgJR82aAEMIChLzeK+b1ZEXQtDHjfKsi3ivvlZmavLps9kz9aNlXHyA7mxCWIZv3YTJ3CUqcAmAYQVHswGYHmWtq2BqPkNzXeQmZ34cOAYz6MIMndhs3afWfhSk0BYCWTshffZw/itogugeWwAZcEUho1OnTPsluh9YJ7tjpZa2XOvHZC1DjQsmzWUbEge905ueEkIaWgce9NyovFl1TqCs9H3XnS3bEfOY+/UDN8YLWwhN7xVZkrG0UjOevYShWDdxeJiPsjizLFAe9Tt376AGK7RGHVubTa2SSDFQeUkmUfm4GsQnWyhGu1XHV+sPR9j8aKA+aXOzrQU4VbTldVSDDtx6YwZ+9I/ie01xTfSN/5mv0lFZnPrq89jv/FtSnjb5gdY5c4TnLjyFHAys63kP+cwzamolCTHObVBgRAZ/qhuZVx7WHi0BTpK5wU42Z9mOdxSKo+U3ktBimNC1XKo2JiK2rfD0d79lFZixcHQB6q5e2UZ/Y9qaN2VIN/6iATzSHZGYQO3EPfOa6JuMKRovrneHurCj67ZJ6WCzp999c7ePIzxkGaHT3pu6bgA4qnC/xNhP2Sg/eG/mGIIngkpMAa4BCnQhv/tO/UxAT7zgSaTdT4O7D8dWrqguq4Y6lHbcAoJ+EL2ahJdG8QYhccI="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
